DROP DATABASE IF EXISTS ucla_04;
CREATE DATABASE ucla_04;

USE ucla_04;

CREATE TABLE notes (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  title VARCHAR(250),
  details TEXT, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);